.*: Assembler messages:
.*: Error: unrecognized opcode `ld x0,8\(x1\)', extension `zilsd' required
.*: Error: unrecognized opcode `ld x8,8\(x8\)', extension `zilsd' required
.*: Error: unrecognized opcode `ld x2,8\(x2\)', extension `zilsd' required
.*: Error: unrecognized opcode `sd x0,8\(x1\)', extension `zilsd' required
.*: Error: unrecognized opcode `sd x8,8\(x8\)', extension `zilsd' required
.*: Error: unrecognized opcode `sd x2,8\(x2\)', extension `zilsd' required
.*: Error: unrecognized opcode `c.sdsp x0,8\(x2\)', extension `zclsd' required
