# Expect script for RISC-V assembler tests.
#   Copyright (C) 2011-2024 Free Software Foundation, Inc.
#
# This file is part of the GNU Binutils.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston,
# MA 02110-1301, USA.

if {[istarget "riscv*-*-*"]} {

    set all_tests [lsort [glob -nocomplain $srcdir/$subdir/*.d]]

    set filtered_tests {}

    if {[info exists ::env(SKIP_V5)] && $::env(SKIP_V5) == "1"} {
	foreach t $all_tests {
	    set base [file tail $t]
	    if {![string match "x-andes*" $base] &&
		![string match "xnexecit*" $base] &&
		![string match "xefhw*" $base]} {
		lappend filtered_tests $t
	    }
	}
    } else {
	set filtered_tests $all_tests
    }

    run_dump_tests $filtered_tests
    run_list_test "align-1"
}
